### ISSUE TITLE
Caramel recipe not working

### ISSUE THREAD

**Issue by Cyphiegorawr** [ShadowStation/ShadowStation#115]
Issue reported from  Round ID: 507 (Shadow Station)

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: 507
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Can't make caramel as it states on the wiki, either it's wrong or the recipe does not work. There seems to be no apparent way to make it in the kitchen either? Went to chemist to heat sugar as directed in TG food and drink wiki, but all we got was just hot sugar. This was to make a birthday cake bounty, but without that ingredient I can't complete it.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShrkByte** [comment]
This is because the recipe for birthday cake is not updated to be the same as tg's.

Currently the recipe calls for a plain cake and a cakehat. (the one found in the bar.)

Will look into working in the proper recipe soon.
