### ISSUE TITLE
Delta Station Cargo belt.

### ISSUE THREAD

**Issue by Zaiakusin** [ShadowStation/ShadowStation#124]
Minor Bug found in Delta Station's cargo loading/offloading belts.  One of the offloading belts is controlled by the loading lever.

Attached is an image of what I mean.  The X is the piece of convayer that is controlled by the lever marked O
![Untitled](https://user-images.githubusercontent.com/54346105/63404616-707db580-c3be-11e9-9a7a-4acb34d280fc.png)

**Comment by TheMocheeze** [comment]
See https://github.com/ShadowStation/ShadowStation/pull/165 it's just an id flag change on that conveyor piece.

**Comment by ShrkByte** [comment]
Fixed by https://github.com/ShadowStation/ShadowStation/pull/165
