### ISSUE TITLE
Away Missions: The Beach Map

### ISSUE THREAD

**Issue by Hunnewle** [ShadowStation/ShadowStation#154]
The Beach Map for away missions appears either broken or unfinished.
Despite VV showing the turfs start with air, I found it vented completely (Potential lag source?) With that said, it also lacks the 'challenge' aspect of the other maps.

No hostiles to fight, no danger to overcome, no loot.

**Comment by Zaiakusin** [comment]
Looked into the files and found two beach maps.  The one in question is most likely beach.dmm.
The issue with this one is that all edges of this area are enclosed with nothing but space.  The other beach map, beach2.dmm, is surrounded by dense rock, much like an asteroid.

Both maps, however, lack any sort of mobs outside of crabs...basic crabs.

**Comment by ShrkByte** [comment]
fixed by https://github.com/ShadowStation/ShadowStation/pull/159
