### ISSUE TITLE
Mannitol not mixing in chemical container

### ISSUE THREAD

**Issue by caballs** [ShadowStation/ShadowStation#35]
Issue reported from  Round ID: 189 (Shadow Station)

Reporting client version: 512

[Round ID]: # 189

[Reproduction]: # Hydrogen, Sugar, and Water do not mix into mannitol.
Could this have something to do with the latest merge for neurine?

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShrkByte** [comment]
Confirmed this is indeed a bug. Seemingly unrelated to the Neurine merge, but i'd appreciate another set of eyes. 

Neurine PR: https://github.com/ShadowStation/ShadowStation/pull/24
