### ISSUE TITLE
Psicodine isnt craftable based on the recipee found on tgstation13.org

### ISSUE THREAD

**Issue by Caralamelia** [ShadowStation/ShadowStation#40]
Issue reported from  Round ID: 211 (Shadow Station)

Reporting client version: 512

[Round ID]: # 211

[Reproduction]: # Create 2 beakers 1 with 20 units of mannitol the second with at least 10 units of impedrezene. dump both units into a large beaker and use the chemaster to add 20 units of water. this should based on the wiki create Psicodine but instead it just doesnt react

**Comment by ShrkByte** [comment]
Psicodine currently is not in the code, only Neurine was ported recently.

There are currently no plans to port Psicodine into the codebase, as it directly conflicts with several systems that were removed from/modified in our codebase.

If you or anyone willing would like to attempt to port Psicodine and make it actually work, go for it.
